# config file

# Size of labeled data to load (i.e. number of jets). Recommended split: 80/10/10
# The qvsg dataset has 2M jets, the ZvsQCD dataset currently has 2M jets, but we can download more if needed (although training would be tough). 
n_train: 30000
n_val:   2500
n_test:  2500

n_part: 20 # how many particles to consider in each graph/jet.

models: ['EdgeNet']

EdgeNet: 
  graph_types: ['fully_connected'] 
  batch_size: 512
  epochs: 70

  learning_rate: 0.01 # 0.01 seems to be the best for the EdgeNet
  patience: 3
  lossname: 'MSE'
  n_sig: 10000
  n_bkg: 10000
  
GATAE:
  graph_types: ['fully_connected']
  heads: 2
  batch_size: 512
  epochs: 7

  learning_rate: 0.001
  patience: 3
  lossname: 'MSE'
  n_sig: 10000
  n_bkg: 10000

transformer:
  batch_size: 512
  epochs: 10

  learning_rate: 0.001 # 0.001 seems to be the best for the transformer
  patience: 1
  lossname: 'MSE'
  n_sig: 10000
  n_bkg: 10000
  input_dim:      3
  pair_input_dim: 3
  

transformer_graph:
  batch_size: 512
  epochs: 20

  learning_rate: 0.03 # 0.001 seems to be the best for the transformer
  patience: 1
  lossname: 'MSE'
  n_sig: 10000
  n_bkg: 10000

  graph: 'laman_knn_graph'
  input_dim:      3
  pair_input_dim: 3
  add_angles: 0 
