# config file

# Size of labeled data to load (i.e. number of jets). Recommended split: 80/10/10
# The qvsg dataset has 2M jets, the ZvsQCD dataset currently has 2M jets, but we can download more if needed (although training would be tough). 
n_train: 15000
n_val:   1500
n_test:  1500

n_part: 100 # how many particles to consider in each graph/jet.

models: ['transformer']

EdgeNet: 
  graph_types: ['fully_connected'] 
  batch_size: 512
  epochs: 2
  learning_rate: 0.01
  patience: 5
  lossname: 'MSE'
  n_sig: 10000
  n_bkg: 10000
  
GATAE:
  graph_types: ['fully_connected']
  heads: 2
  batch_size: 512
  epochs: 7
  learning_rate: 0.001
  patience: 3
  lossname: 'MSE'
  n_sig: 10000
  n_bkg: 10000

transformer:
  batch_size: 512
  epochs: 10
  learning_rate: 0.001
  patience: 3
  lossname: 'MSE'
  n_sig: 10000
  n_bkg: 10000
  input_dim:      1
  pair_input_dim: 4
  